title: Dr. Feng Guo
description: "Measurement • Machine Learning • Methods"
url: "https://FengGuo-IOPsyc.github.io"
baseurl: ""

timezone: America/New_York

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  people:
    output: true
    permalink: /people/:name/
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
      read_time: false
  - scope:
      path: ""
      type: "people"
    values:
      layout: "single"
      author_profile: false
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"
      author_profile: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: false

# Site identity
name: "Workplace Measurement & Analytics Lab (WMA Lab)"
logo: "/assets/img/logo.png"

author:
  name: "Feng Guo, Ph.D."
  avatar: "/assets/img/logo.png"
  bio: "Assistant Professor of Psychology, University of Tennessee at Chattanooga. Research in measurement, machine learning, and methods for selection, testing, and performance."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:feng-guo@utc.edu"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=gO4QNdgAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FengGuo-IOPsyc"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:feng-guo@utc.edu"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=gO4QNdgAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FengGuo-IOPsyc"

excerpt_separator: "<!--more-->"

markdown: kramdown
kramdown:
  input: GFM
permalink: /:categories/:title/
include: ["_pages", ".well-known"]
exclude:
  - "node_modules"
  - "vendor"
  - "README.md"
  - "Gemfile.lock"
  - ".github"
